FROM ubuntu:latest

RUN apt update && apt install -y libboost-dev \
                                 libboost-program-options-dev \
                                 libboost-system-dev \
                                 libboost-thread-dev \
                                 libboost-math-dev \
                                 libboost-test-dev \
                                 zlib1g-dev \
                                 cmake \
                                 g++ \
                                 git

# TODO lock down the version
RUN git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
RUN cd vowpal_wabbit && make install && ldconfig

